### ISSUE TITLE
Issue with expression on Ie 11

### ISSUE THREAD

**Issue by Kukks** [tochoromero/aurelia-bootstrap#9]
The following piece of html template( in aubs-pagination.html) seems to cause an error in IE 11:
```
<li class-name.bind="currentPage === page.value ? &apos;active&apos; : &apos;&apos;" repeat.for="page of displayPages">
      <a click.delegate="selectPage(page.value)">${page.title}</a>
      </li>
</li>
```

The error is caused by this specific attr binding expression: `page of displayPages`

The error: 
```
{
   [functions]: ,
   __proto__: { },
   __symbol:hasInstance0.056852180051203466: undefined,
   __symbol:isConcatSpreadable0.056852180051203467: undefined,
   __symbol:iterator0.056852180051203461: undefined,
   __symbol:match0.056852180051203462: undefined,
   __symbol:replace0.056852180051203463: undefined,
   __symbol:search0.056852180051203464: undefined,
   __symbol:species0.056852180051203469: undefined,
   __symbol:split0.056852180051203465: undefined,
   __symbol:toPrimitive0.0568521800512034610: undefined,
   __symbol:toStringTag0.0568521800512034611: undefined,
   __symbol:unscopables0.056852180051203468: undefined,
   description: "Unable to get property 'attrToRemove' of undefined or null reference",
   message: "Unable to get property 'attrToRemove' of undefined or null reference",
   name: "TypeError",
   number: -2146823281,
   stack: "TypeError: Unable to get property 'attrToRemove' of undefined or null reference
   at _compileElement (http://localhost:9000/scripts/vendor-bundle.js:21695:13)
   at _compileNode (http://localhost:9000/scripts/vendor-bundle.js:21410:11)
   at _compileElement (http://localhost:9000/scripts/vendor-bundle.js:21710:11)
   at _compileNode (http://localhost:9000/scripts/vendor-bundle.js:21410:11)
   at _compileElement (http://localhost:9000/scripts/vendor-bundle.js:21710:11)
   at _compileNode (http://localhost:9000/scripts/vendor-bundle.js:21410:11)
   at _compileNode (http://localhost:9000/scripts/vendor-bundle.js:21432:13)
   at compile (http://localhost:9000/scripts/vendor-bundle.js:21379:7)
   at _compileElement (http://localhost:9000/scripts/vendor-bundle.js:21581:9)
   at _compileNode (http://localhost:9000/scripts/vendor-bundle.js:21410:11)"
}
```

**Comment by tochoromero** [comment]
Is it only happening with IE 11?

**Comment by Kukks** [comment]
Same issue on all IE versions below ( once the polyfills are applied) but this seems to be only for that browser.
